<?php

namespace Database\Seeders;

use App\Models\Etudiant;
use App\Models\Group;
use Illuminate\Database\Seeder;

class EtudiantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $etudiants = [
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Mahboub',
                'prenom' => 'Marouane',
                'email' => 'Mahboub.Marouane@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Asraoui',
                'prenom' => 'Saad',
                'email' => 'Asraoui.Saad@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Laziz',
                'prenom' => 'Wiam',
                'email' => 'Laziz.Wiam@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Rakik',
                'prenom' => 'Salma',
                'email' => 'Rakik.Salma@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'El Houmidi',
                'prenom' => 'Zakaria',
                'email' => 'ElHoumidi.Zakaria@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Hamdy',
                'prenom' => 'Yahya',
                'email' => 'Hamdy.Yahya@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Khalidi',
                'prenom' => 'Zouhair',
                'email' => 'Khalidi.Zouhair@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Laassi',
                'prenom' => 'Abdelhadi',
                'email' => 'Laassi.Abdelhadi@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Houmani',
                'prenom' => 'Reda',
                'email' => 'Houmani.Reda@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Ibdrane',
                'prenom' => 'Ayoub',
                'email' => 'Ibdrane.Ayoub@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Abouraja',
                'prenom' => 'Salma',
                'email' => 'Abouraja.Salma@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Adiab',
                'prenom' => 'Abderahmane',
                'email' => 'Adiab.Abderahmane@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Smoughen',
                'prenom' => 'Oussama',
                'email' => 'Smoughen.Oussama@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Latifi',
                'prenom' => 'Salah',
                'email' => 'Latifi.Salah@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Katane',
                'prenom' => 'Souhaib',
                'email' => 'Katane.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Etudiant::insert($etudiants);
    }
}
