<?php

namespace Database\Seeders;

use App\Models\Etudiant;
use App\Models\Group;
use Illuminate\Database\Seeder;

class EtudiantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $observations = [
            'formateur' => [
                'Très bon étudiant.',
                'Étudiant moyen.',
                'Besoin d\'amélioration.',
                'Excellent travail.',
                'Faible performance.'
            ],
            'conseiller' => [
                'Un étudiant très prometteur.',
                'Bon étudiant.',
                'Doit travailler plus dur.',
                'Excellente attitude.',
                'Doit améliorer sa performance.'
            ],
            'cgcp' => [
                'Performance académique remarquable.',
                'Étudiant satisfaisant.',
                'Peut faire beaucoup mieux.',
                'Élève très diligent.',
                'Performance sous la moyenne.'
            ]
        ];

        $etudiants = [
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Mahboub',
                'prenom' => 'Marouane',
                'email' => 'Mahboub.Marouane@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Majdi',
                'prenom' => 'Saad',
                'email' => 'Majdi.Saad@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Anassi',
                'prenom' => 'Wiam',
                'email' => 'Anassi.Wiam@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Ahmadi',
                'prenom' => 'Salma',
                'email' => 'Ahmadi.Salma@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Asouari',
                'prenom' => 'Zakaria',
                'email' => 'Asouari.Zakaria@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Baadim',
                'prenom' => 'Yahya',
                'email' => 'Baadim.Yahya@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Tijani',
                'prenom' => 'Zouhair',
                'email' => 'Tijani.Zouhair@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD101')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Nassri',
                'prenom' => 'Abdelhadi',
                'email' => 'Nassri.Abdelhadi@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Nouali',
                'prenom' => 'Reda',
                'email' => 'Nouali.Reda@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Habtoun',
                'prenom' => 'Ayoub',
                'email' => 'Habtoun.Ayoub@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Boutaj',
                'prenom' => 'Salma',
                'email' => 'Boutaj.Salma@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Kara',
                'prenom' => 'Abderahmane',
                'email' => 'Kara.Abderahmane@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Falahi',
                'prenom' => 'Oussama',
                'email' => 'Falahi.Oussama@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Samadi',
                'prenom' => 'Salah',
                'email' => 'Samadi.Salah@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'ESA202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Bennani',
                'prenom' => 'Souhaib',
                'email' => 'Bennani.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'TSMFM101')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Etudiant::insert($etudiants);
    }
}
