<?php

namespace Database\Seeders;

use App\Models\Etudiant;
use App\Models\Group;
use Illuminate\Database\Seeder;

class EtudiantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $observations = [
            'formateur' => [
                'Très bon étudiant.',
                'Étudiant moyen.',
                'Besoin d\'amélioration.',
                'Excellent travail.',
                'Faible performance.'
            ],
            'conseiller' => [
                'Un étudiant très prometteur.',
                'Bon étudiant.',
                'Doit travailler plus dur.',
                'Excellente attitude.',
                'Doit améliorer sa performance.'
            ],
            'cgcp' => [
                'Performance académique remarquable.',
                'Étudiant satisfaisant.',
                'Peut faire beaucoup mieux.',
                'Élève très diligent.',
                'Performance sous la moyenne.'
            ]
        ];

        $etudiants = [
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Mahboub',
                'prenom' => 'Marouane',
                'email' => 'Mahboub.Marouane@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Asraoui',
                'prenom' => 'Saad',
                'email' => 'Asraoui.Saad@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Laziz',
                'prenom' => 'Wiam',
                'email' => 'Laziz.Wiam@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Rakik',
                'prenom' => 'Salma',
                'email' => 'Rakik.Salma@ofppt.ma',
                'numero_stagiaire' => 1001,
                'numero_parent' => 2001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'El Houmidi',
                'prenom' => 'Zakaria',
                'email' => 'ElHoumidi.Zakaria@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Hamdy',
                'prenom' => 'Yahya',
                'email' => 'Hamdy.Yahya@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Khalidi',
                'prenom' => 'Zouhair',
                'email' => 'Khalidi.Zouhair@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD202')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Laassi',
                'prenom' => 'Abdelhadi',
                'email' => 'Laassi.Abdelhadi@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Houmani',
                'prenom' => 'Reda',
                'email' => 'Houmani.Reda@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Ibdrane',
                'prenom' => 'Ayoub',
                'email' => 'Ibdrane.Ayoub@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Abouraja',
                'prenom' => 'Salma',
                'email' => 'Abouraja.Salma@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][0],
                'observations_conseiller' => $observations['conseiller'][0],
                'observations_cgcp' => $observations['cgcp'][0],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Adiab',
                'prenom' => 'Abderahmane',
                'email' => 'Adiab.Abderahmane@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][1],
                'observations_conseiller' => $observations['conseiller'][1],
                'observations_cgcp' => $observations['cgcp'][1],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Smoughen',
                'prenom' => 'Oussama',
                'email' => 'Smoughen.Oussama@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][2],
                'observations_conseiller' => $observations['conseiller'][2],
                'observations_cgcp' => $observations['cgcp'][2],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Latifi',
                'prenom' => 'Salah',
                'email' => 'Latifi.Salah@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][3],
                'observations_conseiller' => $observations['conseiller'][3],
                'observations_cgcp' => $observations['cgcp'][3],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'cin' => 'BA' . mt_rand(10000, 99999),
                'nom' => 'Katane',
                'prenom' => 'Souhaib',
                'email' => 'Katane.Souhaib@ofppt.ma',
                'numero_stagiaire' => 2000,
                'numero_parent' => 3001,
                'group_id' => Group::where('nom', 'DD201')->first()->id,
                'observations_formateur' => $observations['formateur'][4],
                'observations_conseiller' => $observations['conseiller'][4],
                'observations_cgcp' => $observations['cgcp'][4],
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Etudiant::insert($etudiants);
    }
}
